In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import seaborn as sns

In [2]:
X,_ = make_blobs(n_samples=300, centers=3, random_state=4) #_ : place holder. To receive anything

X

array([[ 2.80492765, -5.49685296],
       [ 8.14714853,  3.98544896],
       [11.42240659,  5.9692263 ],
       [10.71519001,  0.49360207],
       [ 9.16948179,  1.12892974],
       [10.46723726,  4.75590165],
       [ 3.89455221, -5.32062985],
       [ 9.63773799, -0.01713182],
       [10.01439827,  1.97109995],
       [ 9.90801006,  3.88184611],
       [ 4.78163984, -5.20296428],
       [ 2.29191631, -6.70075161],
       [ 6.96082151,  0.33696129],
       [10.72156491, -1.02710809],
       [ 8.68937095,  1.48709629],
       [12.15865063,  4.38637393],
       [ 5.55249939, -5.47348159],
       [ 9.05329421,  4.94563435],
       [ 3.04883721, -5.97378483],
       [ 9.37923199,  0.46379584],
       [ 3.19453583, -5.53228002],
       [ 9.26368536,  6.04176438],
       [ 9.58820432,  6.16588539],
       [ 2.95060298, -5.01222065],
       [ 9.19714932,  4.46168032],
       [ 3.01347506, -5.90302848],
       [ 4.33685754, -5.27351671],
       [ 9.05081742,  4.75422609],
       [10.87238764,  0.35104318],
       [ 8.85771809, -0.04077348],
       [ 4.29533936, -4.86410921],
       [ 9.37814427,  0.98057303],
       [ 9.06890056,  5.04845423],
       [ 2.55347934, -7.00935269],
       [ 9.08839927, -0.33743784],
       [ 2.81380332, -4.56292486],
       [ 9.95549745,  2.56598193],
       [ 3.42722189, -6.45713233],
       [ 8.47793644,  5.58883701],
       [ 8.18378052,  1.29564214],
       [ 4.81331755, -6.78832058],
       [10.43539786,  4.06035276],
       [10.33807502,  5.57868724],
       [ 4.17877374, -6.29215492],
       [ 4.35018422, -7.02519505],
       [ 9.28176954,  4.77161726],
       [ 4.99408035, -6.53413957],
       [ 9.22118534, -0.10017872],
       [ 8.13319632, -0.2236453 ],
       [ 9.07928474,  1.82138747],
       [ 9.1438515 ,  1.78117369],
       [ 8.66369584, -0.18046961],
       [10.89962006,  4.30877985],
       [ 9.04700622,  3.87326363],
       [ 7.88506245,  1.50083021],
       [ 8.7337095 ,  2.49162431],
       [11.37097205,  3.61620363],
       [ 3.84464325, -4.71635676],
       [ 3.05379555, -5.11637389],
       [ 9.43858503,  3.20414826],
       [ 9.84624781,  4.44016304],
       [ 8.22649705,  5.07031913],
       [ 8.26530669,  2.96705005],
       [ 3.48714017, -6.47495276],
       [ 7.25162262,  7.08312347],
       [ 4.57956098, -4.12059897],
       [10.6124154 ,  0.29700045],
       [10.79544727,  5.07178775],
       [ 3.84527711, -6.43459631],
       [ 9.11914784,  4.62425899],
       [ 8.20747511,  5.79087687],
       [ 3.98389665, -5.26709595],
       [ 8.41351459,  1.28838643],
       [ 4.34571708, -4.67886795],
       [ 8.4876455 , -0.15992963],
       [ 5.22573215, -5.21909088],
       [ 5.03794177, -4.90421941],
       [ 9.04950098,  0.05366925],
       [ 5.9327112 , -5.29438382],
       [ 4.53642397, -7.26351095],
       [10.05887117,  1.46120462],
       [ 8.39622818,  1.22550966],
       [ 9.85037563,  1.24509053],
       [ 7.95141975,  3.95922472],
       [ 2.92076167, -4.16282336],
       [11.563957  ,  1.3389402 ],
       [ 3.57474092, -5.70011666],
       [ 9.2179622 ,  4.72220309],
       [ 9.19535004,  1.45271828],
       [ 9.50048972, -0.26430318],
       [ 9.70123476, -0.57025932],
       [ 8.53594615,  4.8864087 ],
       [ 3.17392217, -5.79858263],
       [ 8.46277398,  6.21157145],
       [12.23082188,  4.22105412],
       [ 5.34160225, -6.76514622],
       [ 9.17804258,  4.92883434],
       [ 8.75021339, -0.40539474],
       [ 3.25087416, -6.8132501 ],
       [10.0828593 ,  5.05146141],
       [ 9.88115962,  6.24427341],
       [ 4.97561437, -7.5420409 ],
       [ 8.77572148, -0.59828407],
       [ 9.74865495,  2.67704349],
       [ 9.24633326,  5.40549445],
       [11.37277611,  1.3704917 ],
       [ 8.06982092,  6.42164203],
       [ 3.18999624, -5.55923139],
       [10.27524684,  0.59854311],
       [ 4.9806605 , -6.87509156],
       [ 8.23501274,  1.78248134],
       [10.0405198 ,  3.83900196],
       [ 9.17687804,  5.4301632 ],
       [10.35203622,  4.27668365],
       [ 8.52987986,  5.48968838],
       [10.64820346,  3.79759915],
       [ 4.73846869, -6.52886642],
       [ 9.56284853,  1.99824539],
       [ 2.35116343, -7.03156309],
       [ 9.39577435, -0.49561989],
       [ 4.07861243, -6.06144005],
       [ 9.40806778,  0.21238028],
       [ 8.70181644,  4.18257479],
       [ 8.99114882, -0.28849184],
       [10.29529538,  1.46789265],
       [ 8.7094575 ,  3.95506388],
       [ 9.76566918,  1.27689813],
       [10.83210675,  2.36652453],
       [ 9.49780787,  3.3133489 ],
       [ 3.8923704 , -4.20392476],
       [ 9.33563854,  1.85961068],
       [ 9.06745856,  4.12360001],
       [ 3.17816324, -6.16065338],
       [ 8.67526538,  4.20643546],
       [10.46897011,  1.1254783 ],
       [ 9.38919979,  1.13329119],
       [10.30561483,  3.2629697 ],
       [ 8.93941996,  1.83974936],
       [ 9.20982242,  5.89341384],
       [ 4.11344713, -4.89523453],
       [10.46093431,  3.21331723],
       [ 5.06395769, -5.53969388],
       [ 4.24332291, -5.39746259],
       [ 3.88744944, -4.5572362 ],
       [ 9.75428715,  4.9914125 ],
       [ 4.48994401, -6.27768814],
       [ 9.12157629,  5.39878296],
       [ 4.37945317, -7.37038323],
       [ 9.95412941,  0.73448842],
       [ 4.56804681, -5.67724481],
       [ 9.49906632,  2.934728  ],
       [ 9.63731352,  4.49418887],
       [ 9.26061729,  1.59443532],
       [ 5.97092308, -5.21200981],
       [ 8.84311623,  3.34266242],
       [ 9.2408213 ,  3.87380245],
       [10.10470245,  0.61507844],
       [ 8.60687857,  4.25237454],
       [ 9.54991027,  0.57020007],
       [ 4.43773586, -5.3477041 ],
       [ 8.86793396,  1.04091293],
       [ 3.44502031, -5.58343936],
       [ 7.7234645 ,  4.9417356 ],
       [ 8.79063719,  4.19997464],
       [ 5.02520281, -7.08349454],
       [ 2.26729745, -6.57860574],
       [ 5.70100127, -6.52987081],
       [10.50478434,  1.18730514],
       [ 9.68756079,  3.99585457],
       [10.38150315,  0.53599467],
       [ 3.9336827 , -5.85739613],
       [10.07377051,  6.52618488],
       [ 9.51074436,  3.86655312],
       [10.72051688,  0.89008628],
       [ 8.70673864,  0.57404279],
       [ 4.06890919, -4.07234927],
       [10.44737098,  3.2136937 ],
       [ 3.31465011, -5.8725407 ],
       [ 5.09555562, -7.05790796],
       [ 3.90282677, -6.44486437],
       [ 4.08505678, -6.1988917 ],
       [ 8.99866368,  4.06663019],
       [10.46626654,  4.6551107 ],
       [ 3.49362942, -3.40863809],
       [ 7.84474442,  0.24924807],
       [ 9.62254002,  5.10853796],
       [ 4.30596811, -6.31071494],
       [ 9.37294759,  6.23419128],
       [10.07884389,  1.59539821],
       [ 3.12185305, -5.38401208],
       [10.74366592,  3.75013489],
       [ 3.69874819, -6.03248579],
       [ 4.17468417, -4.11358406],
       [ 9.95533741,  0.81807639],
       [ 9.95926647,  0.85665806],
       [ 4.66855166, -5.93381445],
       [ 3.90515065, -6.28787831],
       [10.02829977,  4.24333778],
       [ 9.05735049,  0.99412153],
       [ 9.51872209,  4.88648304],
       [ 9.64349881,  1.79503185],
       [10.06252442,  4.39385887],
       [ 9.06439343,  1.74115688],
       [ 4.20436976, -4.82857954],
       [ 8.27473118,  5.45237594],
       [ 3.65838086, -6.37541248],
       [ 7.92436925,  1.82454398],
       [11.5441608 ,  2.02227931],
       [ 5.23209957, -5.55252555],
       [ 8.65944835, -1.02136974],
       [ 8.83221655,  1.95062698],
       [ 9.13738741,  2.00340682],
       [ 8.98645401,  4.59168304],
       [10.13583073,  0.96373495],
       [11.81718094,  1.29698838],
       [ 9.34018509,  2.22490319],
       [ 8.80184697,  4.82997269],
       [10.26279086,  2.96669731],
       [10.95783799,  1.01261718],
       [11.0329545 , -0.16816717],
       [ 8.19679821,  1.45456477],
       [ 3.17021431, -5.32169217],
       [ 9.11425776,  4.94844545],
       [10.21143856,  0.76943446],
       [ 9.05427292,  2.83213631],
       [ 8.43515864,  1.37491631],
       [10.11115136,  4.26235459],
       [ 5.37457802, -4.12373671],
       [ 5.62430548, -3.73290712],
       [ 4.11402401, -5.83428343],
       [ 9.42186055,  0.70412081],
       [ 8.2434749 ,  0.41644891],
       [ 9.25911321,  3.7157247 ],
       [ 3.56277628, -4.7076894 ],
       [ 3.34317373, -5.32595236],
       [ 9.45551896,  1.15701527],
       [ 5.77042928, -5.33995716],
       [ 3.988823  , -3.68255028],
       [ 4.64806011, -4.13052519],
       [ 9.5808359 ,  5.88560566],
       [10.51938697,  2.42258144],
       [ 9.38860303, -1.41342865],
       [ 7.60075264,  5.09334301],
       [ 8.35760513,  0.99907772],
       [ 3.68060441, -6.61125326],
       [ 5.34178313, -7.25803404],
       [10.46167584,  4.91854171],
       [10.35215852,  0.73604417],
       [10.654196  ,  4.7679807 ],
       [ 4.17996484, -5.3665125 ],
       [ 8.69289001,  1.54322016],
       [ 6.06208493, -5.7644901 ],
       [ 4.02839862, -5.57206092],
       [10.06393839,  0.99078055],
       [ 5.5822707 , -5.15637779],
       [ 9.37066386,  0.60846514],
       [10.166774  ,  4.34869048],
       [ 8.87705181,  0.61319243],
       [ 9.67284681, -0.20283165],
       [ 9.35589767,  5.30246986],
       [ 4.05186135, -4.41904813],
       [ 3.40120364, -5.14447498],
       [ 8.56185686,  1.1240557 ],
       [ 3.17399141, -4.34201274],
       [ 3.33559091, -7.28272358],
       [ 2.60988882, -4.04587251],
       [ 6.39939958, -6.2120644 ],
       [ 8.3577712 ,  5.09607541],
       [ 3.43540006, -6.73009766],
       [ 9.73589386,  4.82988717],
       [ 3.86050263, -5.51635598],
       [ 8.40420027,  4.22677355],
       [10.97634432, -0.41632061],
       [ 8.92229526, -0.63993225],
       [ 4.72743756, -4.08496937],
       [ 4.05010129, -5.89474546],
       [10.64605223,  3.10125781],
       [10.12719906, -0.89623088],
       [11.42846765,  1.85948594],
       [ 3.4161624 , -4.88563533],
       [11.63953535,  4.38035327],
       [11.8849112 ,  3.83107114],
       [ 9.6963604 ,  4.71916834],
       [ 9.20989214,  1.7467316 ],
       [ 9.03763281,  2.14664757],
       [ 2.37894284, -4.11654543],
       [ 8.66027511,  3.94634334],
       [ 9.05842775,  3.29824509],
       [10.91947103,  0.73746331],
       [ 8.84477826,  0.77318037],
       [ 9.41116474,  4.59262486],
       [ 8.73060572,  3.33470594],
       [ 7.65763189,  0.5107586 ],
       [ 2.84415029, -4.5871727 ],
       [ 4.77247503, -6.64806576],
       [ 7.99313649,  0.93528488],
       [11.45633262,  0.70338631],
       [10.74187367,  2.5005829 ],
       [10.80111632,  5.69648067],
       [10.56981018,  2.5445225 ]])

In [4]:
df_train = pd.DataFrame(data=X, columns=['x1','x2'])

df_train

            x1        x2
0     2.804928 -5.496853
1     8.147149  3.985449
2    11.422407  5.969226
3    10.715190  0.493602
4     9.169482  1.128930
..         ...       ...
295   7.993136  0.935285
296  11.456333  0.703386
297  10.741874  2.500583
298  10.801116  5.696481
299  10.569810  2.544522

[300 rows x 2 columns]

In [6]:
df_train.describe().T

,count,mean,std,min,25%,50%,75%,max
x1,300.0,7.702730,2.741472,2.267297,4.735711,8.837666,9.709900,12.230822
x2,300.0,-0.087257,4.295794,-7.542041,-4.897481,0.972154,3.873398,7.083123

In [7]:
model = KMeans(n_clusters=3, random_state=2143)
model.fit(X)
new_data = np.array([[2,3],[0,4],[3,1]])
pred = model.predict(new_data)

/home/arnaldoch/Documents/Bootcamp_Data_Science/Clases/unsupervised_learning/.venv/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

In [10]:
pred_all = model.predict(X)
pred_all

array([0, 1, 1, 2, 2, 1, 0, 2, 2, 1, 0, 0, 2, 2, 2, 1, 0, 1, 0, 2, 0, 1,
       1, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 0, 1, 1, 0,
       0, 1, 0, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2, 0, 1,
       2, 2, 2, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 2, 2, 1, 2, 1, 0, 2, 0,
       2, 1, 1, 1, 1, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 2, 1,
       0, 1, 2, 2, 1, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 2, 0,
       1, 1, 2, 1, 2, 0, 2, 0, 1, 1, 0, 0, 0, 2, 1, 2, 0, 1, 1, 2, 2, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 0, 0, 2, 2, 0, 0, 1,
       2, 1, 2, 1, 2, 0, 1, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 2, 2,
       1, 2, 0, 0, 1, 2, 1, 0, 2, 0, 0, 2, 0, 2, 1, 2, 2, 1, 0, 0, 2, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 2, 2, 0, 0, 1, 2, 2, 0, 1, 1, 1, 2, 2, 0,
       1, 1, 2, 2, 1, 1, 2, 0, 0, 2, 2, 2, 1, 2], dtype=int32)

In [11]:
df_train['cluster'] = pred_all
df_train

            x1        x2  cluster
0     2.804928 -5.496853        0
1     8.147149  3.985449        1
2    11.422407  5.969226        1
3    10.715190  0.493602        2
4     9.169482  1.128930        2
..         ...       ...      ...
295   7.993136  0.935285        2
296  11.456333  0.703386        2
297  10.741874  2.500583        2
298  10.801116  5.696481        1
299  10.569810  2.544522        2

[300 rows x 3 columns]

In [ ]:
sns.pairplot()